name: deact_gen
description: A sample command-line application.
version: 0.3.2
homepage: https://github.com/blimster/deact/package/tree/main/generator

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  pedantic: ^1.9.0
