name: deact_gen
description: A sample command-line application.
version: 0.4.0
homepage: https://github.com/blimster/deact/package/tree/main/generator

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  pedantic: ^1.9.0
