name: deact_gen
description: A sample command-line application.
version: 0.5.0
homepage: https://github.com/blimster/deact/package/tree/main/generator

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.9.3
  lints: ^5.1.1
