name: deact
description: A web UI framework inspired by React.
version: 0.1.0
author: Oliver Damm <oliver.damm@gmx.de>
homepage: http://www.github.com/blimster/deact

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
    build_runner: ^1.7.0
    build_web_compilers: ^2.7.0
    pedantic: ^1.9.0