name: deact
description: A web UI framework inspired by React. The main building blocks are components, which can be implemented as classes or functions.
version: 1.0.0-nullsafety.1
homepage: https://www.github.com/blimster/deact

environment:
    sdk: ">=2.12.0-0 <3.0.0"

dependencies:
    incremental_dom_bindings: ^2.0.0-nullsafety
    #logging: ^1.0.0-nullsafety

dev_dependencies:
    build_runner: ^1.10.0
    build_web_compilers: ^2.7.0
    pedantic: ^1.10.0-nullsafety
