name: deact
description: A web UI framework inspired by React. The main building blocks are components, which can be implemented as classes or functions.
version: 0.5.1
homepage: https://www.github.com/blimster/deact

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  incremental_dom_bindings: ^1.0.0
  logging: ^0.11.3

dev_dependencies:
  build_runner: ^1.7.0
  build_web_compilers: ^2.7.0
  pedantic: ^1.9.0
