name: deact
description: A web UI framework inspired by React. The main building blocks are components, which can be implemented as classes or functions.
version: 1.1.0
homepage: https://www.github.com/blimster/deact

environment:
    sdk: ">=2.14.0 <3.0.0"

dependencies:
    incremental_dom_bindings: ^2.1.0
    logging: ^1.0.0

dev_dependencies:
    build_runner: ^2.1.4
    build_web_compilers: ^3.2.1
    lints: ^1.0.1
