part of deact;

Element a({
  Object key,
  String accesskey,
  String className,
  bool contenteditable,
  String contextmenu,
  String dir,
  bool draggable,
  String hidden,
  String id,
  String lang,
  bool spellcheck,
  String style,
  int tabindex,
  String title,
  String href,
  String target,
  String rel,
  EventListener<MouseEvent> onclick,
  List<Node> children,
}) {
  return Element._(
    'a',
    key,
    {
      'accesskey': accesskey,
      'className': className,
      'contenteditable': contenteditable,
      'contextmenu': contextmenu,
      'dir': dir,
      'draggable': draggable,
      'hidden': hidden,
      'id': id,
      'lang': lang,
      'spellcheck': spellcheck,
      'style': style,
      'tabindex': tabindex,
      'title': title,
      'href': href,
      'target': target,
      'rel': rel,
    },
    {
      'onclick': onclick,
    },
    children,
  );
}

Element abbr({
  Object key,
  String accesskey,
  String className,
  bool contenteditable,
  String contextmenu,
  String dir,
  bool draggable,
  String hidden,
  String id,
  String lang,
  bool spellcheck,
  String style,
  int tabindex,
  String title,
  EventListener<MouseEvent> onclick,
  List<Node> children,
}) {
  return Element._(
    'abbr',
    key,
    {
      'accesskey': accesskey,
      'className': className,
      'contenteditable': contenteditable,
      'contextmenu': contextmenu,
      'dir': dir,
      'draggable': draggable,
      'hidden': hidden,
      'id': id,
      'lang': lang,
      'spellcheck': spellcheck,
      'style': style,
      'tabindex': tabindex,
      'title': title,
    },
    {
      'onclick': onclick,
    },
    children,
  );
}

Element address({
  Object key,
  String accesskey,
  String className,
  bool contenteditable,
  String contextmenu,
  String dir,
  bool draggable,
  String hidden,
  String id,
  String lang,
  bool spellcheck,
  String style,
  int tabindex,
  String title,
  EventListener<MouseEvent> onclick,
  List<Node> children,
}) {
  return Element._(
    'address',
    key,
    {
      'accesskey': accesskey,
      'className': className,
      'contenteditable': contenteditable,
      'contextmenu': contextmenu,
      'dir': dir,
      'draggable': draggable,
      'hidden': hidden,
      'id': id,
      'lang': lang,
      'spellcheck': spellcheck,
      'style': style,
      'tabindex': tabindex,
      'title': title,
    },
    {
      'onclick': onclick,
    },
    children,
  );
}

Element area({
  Object key,
  String accesskey,
  String className,
  bool contenteditable,
  String contextmenu,
  String dir,
  bool draggable,
  String hidden,
  String id,
  String lang,
  bool spellcheck,
  String style,
  int tabindex,
  String title,
  String shape,
  String coords,
  String href,
  EventListener<MouseEvent> onclick,
  List<Node> children,
}) {
  return Element._(
    'area',
    key,
    {
      'accesskey': accesskey,
      'className': className,
      'contenteditable': contenteditable,
      'contextmenu': contextmenu,
      'dir': dir,
      'draggable': draggable,
      'hidden': hidden,
      'id': id,
      'lang': lang,
      'spellcheck': spellcheck,
      'style': style,
      'tabindex': tabindex,
      'title': title,
      'shape': shape,
      'coords': coords,
      'href': href,
    },
    {
      'onclick': onclick,
    },
    children,
  );
}

Element article({
  Object key,
  String accesskey,
  String className,
  bool contenteditable,
  String contextmenu,
  String dir,
  bool draggable,
  String hidden,
  String id,
  String lang,
  bool spellcheck,
  String style,
  int tabindex,
  String title,
  EventListener<MouseEvent> onclick,
  List<Node> children,
}) {
  return Element._(
    'article',
    key,
    {
      'accesskey': accesskey,
      'className': className,
      'contenteditable': contenteditable,
      'contextmenu': contextmenu,
      'dir': dir,
      'draggable': draggable,
      'hidden': hidden,
      'id': id,
      'lang': lang,
      'spellcheck': spellcheck,
      'style': style,
      'tabindex': tabindex,
      'title': title,
    },
    {
      'onclick': onclick,
    },
    children,
  );
}

Element div({
  Object key,
  String accesskey,
  String className,
  bool contenteditable,
  String contextmenu,
  String dir,
  bool draggable,
  String hidden,
  String id,
  String lang,
  bool spellcheck,
  String style,
  int tabindex,
  String title,
  EventListener<MouseEvent> onclick,
  List<Node> children,
}) {
  return Element._(
    'div',
    key,
    {
      'accesskey': accesskey,
      'className': className,
      'contenteditable': contenteditable,
      'contextmenu': contextmenu,
      'dir': dir,
      'draggable': draggable,
      'hidden': hidden,
      'id': id,
      'lang': lang,
      'spellcheck': spellcheck,
      'style': style,
      'tabindex': tabindex,
      'title': title,
    },
    {
      'onclick': onclick,
    },
    children,
  );
}
