name: deact
description: A web UI framework inspired by React. The main building blocks are components, which can be implemented as classes or functions.
version: 1.4.0
homepage: https://github.com/Blimster/deact/tree/master/package

environment:
    sdk: ">=2.14.0 <3.0.0"

dependencies:
    domino: ^0.8.2
    
dev_dependencies:
    build_runner: ^2.1.4
    build_web_compilers: ^4.0.5
    lints: ^2.1.1
