name: deact
description: A web UI framework inspired by React. The main building blocks are components, which can be implemented as classes or functions.
version: 1.6.0
homepage: https://github.com/Blimster/deact/tree/master/package

environment:
    sdk: '>=3.4.0 <4.0.0'

dependencies:
    web: ^1.1.0
    domino: ^0.9.0
    
dev_dependencies:
    build_runner: ^2.1.4
    build_web_compilers: ^4.0.5
    lints: ^5.1.1
